# TreeLedger – Data Exploration Notebook

## Data Loading

In this section, we load the raw tree datasets into Pandas DataFrames.
Both a small sample dataset and a real municipal tree census dataset are used
to demonstrate and validate the data processing pipeline.

In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/trees_sample.csv")
df

   tree_id species   location  age  height_m
0        1    Neem  Hyderabad   12       5.4
1        2  Banyan  Hyderabad   45      18.2
2        3  Peepal      Delhi   30      14.8
3        4    Neem  Bangalore    8       3.9
4        5    Teak     Kerala   20      11.5

In [2]:
import pandas as pd

real_df = pd.read_csv("../data/raw/urban_tree_census.csv")
real_df.head()

,FID,id,geom,oid,sr_no,girth_cm,height_m,canopy_dia_m,condition,other_remarks,...,ward_name,botanical_name,saar_uid,common_name,local_name,economic_i,phenology,flowering,ward,is_rare
0,trees_display.fid--1672c0a_16c6758e284_-e38,18038741,POINT (73.87415841200004 18.56424356200004),NaN,NaN,26,5,3,Healthy,NaN,...,16,Prosopis juliflora (Sw.)Dc.,4021357,Mesquite,Villayati Babul,Timber wood,Seasonal,October-May,16,False
1,trees_display.fid--1672c0a_16c6758e284_-e37,18038742,POINT (73.87416645900002 18.564220360000025),NaN,NaN,26,5,3,Healthy,NaN,...,16,Prosopis juliflora (Sw.)Dc.,4021359,Mesquite,Villayati Babul,Timber wood,Seasonal,October-May,16,False
2,trees_display.fid--1672c0a_16c6758e284_-e36,18038743,POINT (73.87414600700006 18.56420160800006),NaN,NaN,25,4,3,Healthy,NaN,...,16,Prosopis juliflora (Sw.)Dc.,4021358,Mesquite,Villayati Babul,Timber wood,Seasonal,October-May,16,False
3,trees_display.fid--1672c0a_16c6758e284_-e35,18038744,POINT (73.87407459300003 18.564188259000034),NaN,NaN,26,5,3,Healthy,NaN,...,16,Prosopis juliflora (Sw.)Dc.,4021360,Mesquite,Villayati Babul,Timber wood,Seasonal,October-May,16,False
4,trees_display.fid--1672c0a_16c6758e284_-e34,18038745,POINT (73.87396998700004 18.56422639900006),NaN,NaN,26,6,3,Healthy,NaN,...,16,Prosopis juliflora (Sw.)Dc.,4021361,Mesquite,Villayati Babul,Timber wood,Seasonal,October-May,16,False

## Initial Data Inspection

This section is used to understand the structure and quality of the raw datasets.
Basic inspection functions are applied to examine column names, data types,
dataset size, and potential missing values before any cleaning is performed.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tree_id   5 non-null      int64
 1   species   5 non-null      object
 2   location  5 non-null      object
 3   age       5 non-null      int64
 4   height_m  5 non-null      float64
dtypes: float64(1), int64(2), object(2)
memory usage: 332.0+ bytes

In [4]:
df.columns

Index(['tree_id', 'species', 'location', 'age', 'height_m'], dtype='object')

In [5]:
df.shape

(5, 5)

In [6]:
df.describe()

        tree_id        age   height_m
count  5.000000   5.000000   5.000000
mean   3.000000  23.000000  10.760000
std    1.581139  14.899664   6.083009
min    1.000000   8.000000   3.900000
25%    2.000000  12.000000   5.400000
50%    3.000000  20.000000  11.500000
75%    4.000000  30.000000  14.800000
max    5.000000  45.000000  18.200000

In [7]:
df["species"].value_counts()

species
Neem      2
Banyan    1
Peepal    1
Teak      1
Name: count, dtype: int64

In [8]:
df.head()

   tree_id species   location  age  height_m
0        1    Neem  Hyderabad   12       5.4
1        2  Banyan  Hyderabad   45      18.2
2        3  Peepal      Delhi   30      14.8
3        4    Neem  Bangalore    8       3.9
4        5    Teak     Kerala   20      11.5

In [9]:
df.isnull().sum()

tree_id     0
species     0
location    0
age         0
height_m    0
dtype: int64

In [10]:
df.groupby("location")["tree_id"].count()

location
Bangalore    1
Delhi        1
Hyderabad    2
Kerala       1
Name: tree_id, dtype: int64

In [11]:
real_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9623 entries, 0 to 9622
Data columns (total 28 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   FID             9623 non-null   object
 1   id              9623 non-null   int64
 2   geom            9623 non-null   object
 3   oid             0 non-null      float64
 4   sr_no           0 non-null      float64
 5   girth_cm        9623 non-null   int64
 6   height_m        9623 non-null   int64
 7   canopy_dia_m    9623 non-null   int64
 8   condition       9623 non-null   object
 9   other_remarks   0 non-null      float64
 10  ownership       9623 non-null   object
 11  society_name    9423 non-null   object
 12  road_name       9623 non-null   object
 13  northing        9623 non-null   float64
 14  easting         9623 non-null   float64
 15  balanced        9623 non-null   bool
 16  remarks         5027 non-null   object
 17  special_collar  377 non-null    object
 18  ward_name       9623 non-null   int64
 19  botanical_name  9580 non-null   object
 20  saar_uid        9623 non-null   int64
 21  common_name     9623 non-null   object
 22  local_name      9623 non-null   object
 23  economic_i      9580 non-null   object
 24  phenology       9553 non-null   object
 25  flowering       9552 non-null   object
 26  ward            9623 non-null   int64
 27  is_rare         9580 non-null   object
dtypes: bool(1), float64(5), int64(7), object(15)
memory usage: 2.0+ MB

In [12]:
real_df.columns

Index(['FID', 'id', 'geom', 'oid', 'sr_no', 'girth_cm', 'height_m',
       'canopy_dia_m', 'condition', 'other_remarks', 'ownership',
       'society_name', 'road_name', 'northing', 'easting', 'balanced',
       'remarks', 'special_collar', 'ward_name', 'botanical_name', 'saar_uid',
       'common_name', 'local_name', 'economic_i', 'phenology', 'flowering',
       'ward', 'is_rare'],
      dtype='object')

In [13]:
real_df.shape

(9623, 28)

## Data Cleaning

This section applies a reusable data cleaning pipeline to both the sample dataset
and the real urban tree census dataset. The cleaning process standardizes column
names, removes unnecessary whitespace, ensures numeric consistency, and exports
processed CSV files for further analysis.

In [14]:
import sys
sys.path.append("../src")

from data_cleaning import clean_tree_data

cleaned_df = clean_tree_data(
    "../data/raw/trees_sample.csv",
    "../data/processed/trees_cleaned.csv"
)

In [15]:
cleaned_real_df = clean_tree_data(
    "../data/raw/urban_tree_census.csv",
    "../data/processed/urban_tree_census_cleaned.csv"
)

### Play check of real data after data cleaning

In [16]:
cleaned_real_df.head()

,fid,id,oid,sr_no,girth_cm,height_m,canopy_dia_m,condition,ownership,society_name,...,ward_name,botanical_name,saar_uid,common_name,local_name,economic_i,phenology,flowering,ward,is_rare
0,trees_display.fid--1672c0a_16c6758e284_-e38,18038741,NaN,NaN,26,5,3,Healthy,Public,N/A,...,16,Prosopis juliflora (Sw.)Dc.,4021357,Mesquite,Villayati Babul,Timber wood,Seasonal,October-May,16,False
1,trees_display.fid--1672c0a_16c6758e284_-e37,18038742,NaN,NaN,26,5,3,Healthy,Public,N/A,...,16,Prosopis juliflora (Sw.)Dc.,4021359,Mesquite,Villayati Babul,Timber wood,Seasonal,October-May,16,False
2,trees_display.fid--1672c0a_16c6758e284_-e36,18038743,NaN,NaN,25,4,3,Healthy,Public,N/A,...,16,Prosopis juliflora (Sw.)Dc.,4021358,Mesquite,Villayati Babul,Timber wood,Seasonal,October-May,16,False
3,trees_display.fid--1672c0a_16c6758e284_-e35,18038744,NaN,NaN,26,5,3,Healthy,Public,N/A,...,16,Prosopis juliflora (Sw.)Dc.,4021360,Mesquite,Villayati Babul,Timber wood,Seasonal,October-May,16,False
4,trees_display.fid--1672c0a_16c6758e284_-e34,18038745,NaN,NaN,26,6,3,Healthy,Public,N/A,...,16,Prosopis juliflora (Sw.)Dc.,4021361,Mesquite,Villayati Babul,Timber wood,Seasonal,October-May,16,False

In [17]:
cleaned_real_df.columns

Index(['fid', 'id', 'oid', 'sr_no', 'girth_cm', 'height_m', 'canopy_dia_m',
       'condition', 'ownership', 'society_name', 'road_name', 'northing',
       'easting', 'balanced', 'special_collar', 'ward_name', 'botanical_name',
       'saar_uid', 'common_name', 'local_name', 'economic_i', 'phenology',
       'flowering', 'ward', 'is_rare'],
      dtype='object')

In [18]:
cleaned_real_df.shape

(9623, 25)

In [19]:
cleaned_real_df.isnull().sum().head(10)

fid                0
id                 0
oid             9623
sr_no           9623
girth_cm           0
height_m           0
canopy_dia_m       0
condition          0
ownership          0
society_name       0
dtype: int64

In [20]:
trees_per_ward = cleaned_real_df["ward_name"].value_counts()
trees_per_ward.head(10)

ward_name
9     2898
24    2566
41    1652
8      715
16     514
1      442
31     282
30     227
45     155
46      60
Name: count, dtype: int64

In [21]:
top_species = cleaned_real_df["common_name"].value_counts().head(10)

In [22]:
cleaned_real_df[["height_m", "girth_cm", "canopy_dia_m"]].describe()

          height_m     girth_cm  canopy_dia_m
count  9623.000000  9623.000000   9623.000000
mean      6.579653    52.264055      3.947106
std       3.784255    54.331559      3.558784
min       2.000000     8.000000      0.000000
25%       4.000000    23.000000      2.000000
50%       6.000000    35.000000      3.000000
75%       8.000000    60.000000      5.000000
max      24.000000   686.000000     43.000000

## Data Analysis

This section performs exploratory and statistical analysis on the cleaned
datasets. Key insights such as tree distribution across wards, dominant tree
species, and summary statistics are derived and visualized to support
environmental understanding.

In [23]:
import sys
sys.path.append("../src")

from analysis import analyze_tree_data

result = analyze_tree_data(
    "../data/processed/trees_cleaned.csv",
    "../outputs/plots/trees_per_location.png"
)

result

location
Bangalore    1
Delhi        1
Hyderabad    2
Kerala       1
Name: tree_id, dtype: int64

In [24]:
import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))
trees_per_ward.head(10).plot(kind="bar")
plt.title("Top 10 Wards by Tree Count")
plt.ylabel("Number of Trees")
plt.tight_layout()
plt.savefig("../outputs/plots/trees_per_ward_real.png")
plt.close()

### Final Analysis Using Project Module

In [25]:
import sys
sys.path.append("../src")

from analysis_real import analyze_real_tree_data

results = analyze_real_tree_data(
    "../data/processed/urban_tree_census_cleaned.csv",
    "../outputs/plots"
)

results

{'trees_per_ward': ward_name
 9     2898
 24    2566
 41    1652
 8      715
 16     514
 1      442
 31     282
 30     227
 45     155
 46      60
 7       59
 6       38
 71      14
 61       1
 Name: count, dtype: int64,
 'top_species': common_name
 Subabul             2946
 Giripushpa          1277
 Gum Arabic Tree      446
 Mesquite             431
 Neem                 354
 Babul                321
 Ashoka (D)           230
 Yellow Bells         213
 Rain Tree            204
 Cluster Fig Tree     180
 Name: count, dtype: int64,
 'height_summary': count    9623.000000
 mean        6.579653
 std         3.784255
 min         2.000000
 25%         4.000000
 50%         6.000000
 75%         8.000000
 max        24.000000
 Name: height_m, dtype: float64}

## Conclusion

The TreeLedger project successfully processed and analyzed a real municipal
urban tree census dataset containing over 9,600 records. The analysis revealed
clear ward-level differences in tree distribution, identified dominant tree
species, and summarized structural characteristics such as tree height and
canopy spread.

This demonstrates the effectiveness of a structured data pipeline for
environmental analysis and highlights how real-world civic datasets can be
cleaned, analyzed, and visualized using Python.